package aa.frieze.wateringflowersbot.domain.enumeration;

public enum BotState {
    SHOW_MAIN_MENU,
    SUBSCRIBE,
    UNSUBSCRIBE,
    VIEW,
    CHANGE_NOTIFICATION,
    CHANGE_TIMEZONE,
    WAITING_FOR_TITLE,
    WAITING_FOR_TIMEZONE,
    WAITING_FOR_START_DATE,
    WAITING_FOR_DURATION,
    UNSUBSCRIBE_ALL,
    UNSUBSCRIBE_CUSTOM,
    VIEW_ALL,
    VIEW_ACTUAL,
    SELECT_NOTIFICATION,
    CHANGE_TITLE,
    CHANGE_NEXT_DATE,
    CHANGE_DURATION
}
