package aa.frieze.wateringflowersbot.domain.enumeration;

public enum BotState {
    SHOW_MAIN_MENU,
    SHOW_SUBSCRIPTIONS_MENU_EMPLOYEE,
    SUBSCRIBE_EMP,
    UNSUBSCRIBE_EMP,
    ASK_MAIL,
    APPLICATIONS_SEARCH,
    APPLICATIONS_SEARCH_PM,
    APPLICATIONS_SEARCH_HOD,
    APPLICATIONS_SEARCH_EMP,
    WORKLOGS_SEARCH,
    WORKLOGS_SEARCH_PM,
    WORKLOGS_SEARCH_HOD,
    WORKLOGS_SEARCH_EMP,
    ASK_WEEK, ASK_STATUS,
    ASK_DATE, ASK_PROJECTS,
    ASK_DEPARTMENTS, ASK_INFO,
    SHOW_WORKLOGS,
    SHOW_HELP_MENU,
    WAIT_WITH_CURRENT_WEEK,
    WAIT_WITH_NEXT_WEEK
}
