version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=watering_flowers
    ports:
      - "5433:5432"
  zookeeper:
    image: watering-flowers-app:1.1.0
    environment:
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PORT=5432
      - DATASOURCE_HOST=postgres
      - BOT_ENABLED=true
      - BOT_NAME=#botname
      - BOT_TOKEN=#token
    ports:
      - "8092:8092"
    depends_on:
     - postgres
